proto < ./studentpb/student.proto
@host=localhost:5060

GRPC /StudentService/GetStudent
{
    "id": "s1"
}

###
GRPC /StudentService/SetStudent
{
    "id": "s3",
    "name": "Student 3",
    "age": 24
}